### PR TITLE
Add support for Stretch

### PR DESCRIPTION
**Pull request by timstoop**
This updates the MAC list for Debian Stretch.

### CODE REVIEW

**Comment by bitvijays** [comment]
@mcgege Hope you are doing well. Thank you for your awesome support on Puppet OS Hardening!. I was wondering. What's the issue with this PR? Is it the fail checks by travis? (which are mainly because of the old files)? I would be happy to work on this. Just let me know if old error/ formats need to be changed.

**Comment by mcgege** [comment]
From my point of view, this repo needs a complete restart - last commit was from 2015. I think best would be to pick one of the up to date implementations (Ansible or Chef) and try to translate this into a (new) Puppet package.
On this specific PR: I don't know, haven't followed this ...

**Comment by bitvijays** [comment]
@mcgege Complete restart would be a really good amount of effort. (which I am afraid would be difficult atm). Let me provide a quick background of this PR (if we can work on this). That's would be really appreciated.

Currently, if we apply ssh_hardening on a Debian 9. SSH service fails to restart after applying the configuration (which makes changes to the sshd_config). As SSH fails to restart, the access to the machine is lost. This is mainly because of unsupported MAC hmac-ripemd160-etm as hmac-ripemd160 is considered weak.

Warning: "hmac-ripemd160" and precheck "hmac-ripemd160-etm" are considered weak keyed-hash message authentication code (HMAC) algorithms and support for the same will be removed.

Currently, $macs in https://github.com/dev-sec/puppet-ssh-hardening/blob/master/manifests/server.pp 

```
$macs = get_ssh_macs($::operatingsystem, $::operatingsystemrelease, $weak_hmac)
```
utilised get_ssh_macs function which comes from https://github.com/dev-sec/puppet-ssh-hardening/blob/master/lib/puppet/parser/functions/get_ssh_macs.rb 

```
  macs_66.default = 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'
```

If we remove repemd160 from the above, we should be good. Let me know your thoughts. Again, Thank you for your support!

**Comment by timstoop** [comment]
I've been trying to get this all to work again as well (not publicly), but ran into my lack of knowledge regarding the ruby specific code. A lot of the linting errors are quite easy to fix, but others require a bit more knowledge about ruby. I think most of the actual puppet code is still pretty useful, although it needs to be upgraded (for which a lot of PRs are still available). If someone could spend the time on getting the rubocop errors under control (or if we maybe even could remove that part of the CI for now?), I'm happy to spend time on the PRs and bringing this repo more up to date.

**Comment by bitvijays** [comment]
@artem-sidorenko Hope you are doing well. It's been really long. I was wondering what would be the way forward to revive this puppet-ssh-hardening? I would be happy to manage this repo? (atleast bring back it to life). Let me know how can I help?

At first, I was thinking to update rubocop.yml  (as it is in puppet_os_hardening) and then fix the remaining errors. Let me know your thoughts.

**Pull request closed without merging**
